export interface SchemaProperty {
  name: string;
  expectedType: string;
  description: string;
}

export interface SchemaType {
  name: string;
  description: string;
  parent: string;
  hierarchy: string[];
  properties: SchemaProperty[];
}

export const schemaTypes: SchemaType[] = [
  {
    name: "Book",
    description:
      "A book. For individual chapters, use the Chapter type.",
    parent: "CreativeWork",
    hierarchy: ["Thing", "CreativeWork", "Book"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name/title of the book" },
      { name: "author", expectedType: "Person", description: "The author of the book" },
      { name: "isbn", expectedType: "Text", description: "The ISBN of the book" },
      { name: "numberOfPages", expectedType: "Integer", description: "Number of pages in the book" },
      { name: "bookFormat", expectedType: "BookFormatType", description: "The format of the book (e.g. Paperback, Hardcover, EBook)" },
      { name: "publisher", expectedType: "Organization", description: "The publisher of the book" },
      { name: "datePublished", expectedType: "Date", description: "Date of publication" },
      { name: "inLanguage", expectedType: "Text", description: "The language of the content" },
      { name: "description", expectedType: "Text", description: "A description of the item" },
      { name: "genre", expectedType: "Text", description: "Genre of the creative work" },
    ],
  },
  {
    name: "Person",
    description: "A person (alive, dead, undead, or fictional).",
    parent: "Thing",
    hierarchy: ["Thing", "Person"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the person" },
      { name: "givenName", expectedType: "Text", description: "Given name (first name)" },
      { name: "familyName", expectedType: "Text", description: "Family name (last name)" },
      { name: "email", expectedType: "Text", description: "Email address" },
      { name: "jobTitle", expectedType: "Text", description: "The person's job title" },
      { name: "affiliation", expectedType: "Organization", description: "An organization this person is affiliated with" },
      { name: "birthDate", expectedType: "Date", description: "Date of birth" },
      { name: "url", expectedType: "URL", description: "URL of the person's page" },
      { name: "image", expectedType: "URL", description: "An image of the person" },
    ],
  },
  {
    name: "Organization",
    description: "An organization such as a school, NGO, corporation, club, etc.",
    parent: "Thing",
    hierarchy: ["Thing", "Organization"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the organization" },
      { name: "url", expectedType: "URL", description: "URL of the organization" },
      { name: "logo", expectedType: "URL", description: "Logo of the organization" },
      { name: "address", expectedType: "PostalAddress", description: "Physical address" },
      { name: "telephone", expectedType: "Text", description: "Telephone number" },
      { name: "email", expectedType: "Text", description: "Email address" },
      { name: "foundingDate", expectedType: "Date", description: "Date the organization was founded" },
      { name: "employee", expectedType: "Person", description: "Someone working for this organization" },
    ],
  },
  {
    name: "Dataset",
    description:
      "A body of structured information describing some topic(s) of interest.",
    parent: "CreativeWork",
    hierarchy: ["Thing", "CreativeWork", "Dataset"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the dataset" },
      { name: "description", expectedType: "Text", description: "A description of the dataset" },
      { name: "creator", expectedType: "Person", description: "The creator/author of the dataset" },
      { name: "dateCreated", expectedType: "Date", description: "Date of creation" },
      { name: "license", expectedType: "URL", description: "A license document that applies to this content" },
      { name: "distribution", expectedType: "DataDownload", description: "A downloadable form of this dataset" },
      { name: "temporalCoverage", expectedType: "Text", description: "The time period the dataset covers" },
      { name: "spatialCoverage", expectedType: "Place", description: "The geographic area the dataset covers" },
      { name: "variableMeasured", expectedType: "Text", description: "The variables measured in the dataset" },
    ],
  },
  {
    name: "Event",
    description: "An event happening at a certain time and location.",
    parent: "Thing",
    hierarchy: ["Thing", "Event"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the event" },
      { name: "startDate", expectedType: "DateTime", description: "The start date and time" },
      { name: "endDate", expectedType: "DateTime", description: "The end date and time" },
      { name: "location", expectedType: "Place", description: "The location of the event" },
      { name: "organizer", expectedType: "Organization", description: "The organizer of the event" },
      { name: "performer", expectedType: "Person", description: "A performer at the event" },
      { name: "description", expectedType: "Text", description: "A description of the event" },
      { name: "eventStatus", expectedType: "EventStatusType", description: "Status of the event (scheduled, cancelled, etc.)" },
      { name: "offers", expectedType: "Offer", description: "Ticket or admission information" },
    ],
  },
  {
    name: "Recipe",
    description: "A recipe. For diet-related content, consider the Diet type.",
    parent: "CreativeWork",
    hierarchy: ["Thing", "CreativeWork", "HowTo", "Recipe"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the recipe" },
      { name: "author", expectedType: "Person", description: "The author of the recipe" },
      { name: "cookTime", expectedType: "Duration", description: "Time it takes to cook" },
      { name: "prepTime", expectedType: "Duration", description: "Time it takes to prepare" },
      { name: "recipeIngredient", expectedType: "Text", description: "An ingredient used in the recipe" },
      { name: "recipeInstructions", expectedType: "Text", description: "Steps to make the recipe" },
      { name: "recipeYield", expectedType: "Text", description: "Quantity produced by the recipe" },
      { name: "nutrition", expectedType: "NutritionInformation", description: "Nutrition information" },
      { name: "recipeCategory", expectedType: "Text", description: "The category (e.g. appetizer, main course)" },
      { name: "image", expectedType: "URL", description: "An image of the dish" },
    ],
  },
  {
    name: "Movie",
    description: "A movie.",
    parent: "CreativeWork",
    hierarchy: ["Thing", "CreativeWork", "Movie"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the movie" },
      { name: "director", expectedType: "Person", description: "The director of the movie" },
      { name: "actor", expectedType: "Person", description: "An actor in the movie" },
      { name: "duration", expectedType: "Duration", description: "The duration of the movie" },
      { name: "genre", expectedType: "Text", description: "Genre of the movie" },
      { name: "datePublished", expectedType: "Date", description: "Release date" },
      { name: "description", expectedType: "Text", description: "A description of the movie" },
      { name: "productionCompany", expectedType: "Organization", description: "The production company" },
      { name: "aggregateRating", expectedType: "AggregateRating", description: "Overall rating" },
    ],
  },
  {
    name: "LocalBusiness",
    description: "A particular physical business or branch of an organization.",
    parent: "Organization",
    hierarchy: ["Thing", "Organization", "LocalBusiness"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the business" },
      { name: "address", expectedType: "PostalAddress", description: "Physical address" },
      { name: "telephone", expectedType: "Text", description: "Telephone number" },
      { name: "openingHours", expectedType: "Text", description: "Opening hours specification" },
      { name: "priceRange", expectedType: "Text", description: "Price range (e.g. $$$)" },
      { name: "geo", expectedType: "GeoCoordinates", description: "Geographic coordinates" },
      { name: "image", expectedType: "URL", description: "An image of the business" },
      { name: "url", expectedType: "URL", description: "URL of the business website" },
      { name: "aggregateRating", expectedType: "AggregateRating", description: "Overall rating" },
    ],
  },
  {
    name: "Course",
    description: "A description of an educational course.",
    parent: "CreativeWork",
    hierarchy: ["Thing", "CreativeWork", "LearningResource", "Course"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the course" },
      { name: "description", expectedType: "Text", description: "A description of the course" },
      { name: "provider", expectedType: "Organization", description: "The organization offering the course" },
      { name: "instructor", expectedType: "Person", description: "The instructor of the course" },
      { name: "courseCode", expectedType: "Text", description: "The course identifier (e.g. LIS 4220)" },
      { name: "educationalLevel", expectedType: "Text", description: "The level of the course (e.g. Graduate)" },
      { name: "inLanguage", expectedType: "Text", description: "Language of instruction" },
      { name: "hasCourseInstance", expectedType: "CourseInstance", description: "A specific offering of the course" },
    ],
  },
  {
    name: "MusicRecording",
    description: "A music recording (track).",
    parent: "CreativeWork",
    hierarchy: ["Thing", "CreativeWork", "MusicRecording"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the track" },
      { name: "byArtist", expectedType: "Person", description: "The artist who performed this" },
      { name: "inAlbum", expectedType: "MusicAlbum", description: "The album this track is on" },
      { name: "duration", expectedType: "Duration", description: "Duration of the track" },
      { name: "genre", expectedType: "Text", description: "Genre of the recording" },
      { name: "datePublished", expectedType: "Date", description: "Date of release" },
      { name: "isrcCode", expectedType: "Text", description: "International Standard Recording Code" },
    ],
  },
  {
    name: "SoftwareApplication",
    description: "A software application.",
    parent: "CreativeWork",
    hierarchy: ["Thing", "CreativeWork", "SoftwareApplication"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the application" },
      { name: "operatingSystem", expectedType: "Text", description: "Operating systems supported" },
      { name: "applicationCategory", expectedType: "Text", description: "Type of application (e.g. GameApplication)" },
      { name: "downloadUrl", expectedType: "URL", description: "URL to download the software" },
      { name: "softwareVersion", expectedType: "Text", description: "Version of the software" },
      { name: "offers", expectedType: "Offer", description: "Pricing information" },
      { name: "aggregateRating", expectedType: "AggregateRating", description: "Overall rating" },
      { name: "description", expectedType: "Text", description: "A description of the software" },
    ],
  },
  {
    name: "WebPage",
    description: "A web page.",
    parent: "CreativeWork",
    hierarchy: ["Thing", "CreativeWork", "WebPage"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the web page" },
      { name: "url", expectedType: "URL", description: "URL of the page" },
      { name: "description", expectedType: "Text", description: "A description of the page" },
      { name: "lastReviewed", expectedType: "Date", description: "Date last reviewed for accuracy" },
      { name: "mainEntity", expectedType: "Thing", description: "The primary entity described on this page" },
      { name: "breadcrumb", expectedType: "Text", description: "Breadcrumb navigation" },
      { name: "isPartOf", expectedType: "WebSite", description: "The website this page belongs to" },
    ],
  },
  {
    name: "Place",
    description: "Entities that have a somewhat fixed, physical extension.",
    parent: "Thing",
    hierarchy: ["Thing", "Place"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name of the place" },
      { name: "address", expectedType: "PostalAddress", description: "Physical address" },
      { name: "geo", expectedType: "GeoCoordinates", description: "Geographic coordinates" },
      { name: "telephone", expectedType: "Text", description: "Telephone number" },
      { name: "openingHoursSpecification", expectedType: "OpeningHoursSpecification", description: "Opening hours" },
      { name: "photo", expectedType: "URL", description: "A photo of the place" },
      { name: "containedInPlace", expectedType: "Place", description: "The larger place this is contained within" },
      { name: "url", expectedType: "URL", description: "URL of the place's page" },
    ],
  },
  {
    name: "VideoObject",
    description: "A video file.",
    parent: "CreativeWork",
    hierarchy: ["Thing", "CreativeWork", "MediaObject", "VideoObject"],
    properties: [
      { name: "name", expectedType: "Text", description: "The name/title of the video" },
      { name: "description", expectedType: "Text", description: "A description of the video" },
      { name: "thumbnailUrl", expectedType: "URL", description: "Thumbnail image" },
      { name: "uploadDate", expectedType: "Date", description: "Date when the video was uploaded" },
      { name: "duration", expectedType: "Duration", description: "Duration of the video" },
      { name: "contentUrl", expectedType: "URL", description: "URL of the actual video content" },
      { name: "embedUrl", expectedType: "URL", description: "URL to embed the video" },
      { name: "interactionStatistic", expectedType: "InteractionCounter", description: "View count and other stats" },
    ],
  },
];

export const exerciseWebsites = [
  {
    name: "Denver Zoo",
    url: "https://www.denverzoo.org",
    hint: "Think about what type of organization this is, its location, events, hours...",
  },
  {
    name: "A YouTube Video",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    hint: "What schema.org type describes a video? What properties matter most?",
  },
  {
    name: "University of Denver Homepage",
    url: "https://www.du.edu",
    hint: "Is this an Organization? An EducationalOrganization? What properties describe a university?",
  },
  {
    name: "Denver Public Library",
    url: "https://www.denverlibrary.org",
    hint: "Libraries are organizations with locations, collections, events, hours...",
  },
  {
    name: "An Internet Archive Game",
    url: "https://archive.org/details/msdos_Oregon_Trail_The_1990",
    hint: "What type is a software application / game? How would you describe a preserved digital artifact?",
  },
];
